trigger:
  - master
  - refs/tags/*

jobs:
- template: ci-jobs.yml

- template: ci-jobs.yml
  parameters:
    name: macOS
    vmImage: 'macOS-10.13'

- template: ci-jobs.yml
  parameters:
    name: Windows
    vmImage: 'vs2017-win2016'

- job: Publish
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Linux Artifacts'
    inputs:
      artifactName: LinuxBinary
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - task: DownloadBuildArtifacts@0
    displayName: 'Download macOS Artifacts'
    inputs:
      artifactName: macOSBinary
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Windows Artifacts'
    inputs:
      artifactName: WindowsBinary
      downloadPath: '$(System.DefaultWorkingDirectory)'
  - script: |
      mkdir prebuilds
      mv LinuxBinary/* prebuilds
      mv macOSBinary/* prebuilds
      mv WindowsBinary/* prebuilds
  - script: npm publish
    env:
      NPM_TOKEN: $(secret_npm_token)
  dependsOn:
  - Windows
  - Linux
  - macOS
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
