parameters:
  name: 'Linux'
  vmImage: 'ubuntu-16.04'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: npm test
    displayName: 'npm test'

  - script: npm run prebuild
    displayName: 'npm prebuild'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/prebuilds'
      artifactName: ${{ format('{0}Binary', parameters.name) }}
